[package]
name = "calculator"
version = "0.1.0"
authors = ["Akira Hasegawa <akira.hasegawa@jaist.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.0"
rustyline = "7.1.0"
